# Generated by Django 4.2.2 on 2023-06-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Paxta navi')),
                ('usish_davri', models.CharField(blank=True, max_length=10, null=True, verbose_name="O'sish davri")),
                ('uzunlik', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tola uzunligi')),
                ('hosildorlik', models.CharField(blank=True, max_length=10, null=True, verbose_name='Hosildorligi')),
                ('tola_tipi', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tola tipi')),
                ('nisbiy_kuch', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nisbiy uzunlik kuchi')),
                ('nav_guruxi', models.CharField(blank=True, max_length=30, null=True, verbose_name='Paxta navlari guruxi')),
                ('tola_chiqishi', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tola chiqishi')),
                ('tola_pishiqligi', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tolaning pishiqligi')),
                ('country', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mamlakat')),
                ('popular', models.BooleanField(default=False, verbose_name='Mashxur nav')),
            ],
        ),
    ]
