# Generated by Django 4.2.2 on 2023-06-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_cotton_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotton',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mamlakat'),
        ),
    ]
